spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jwt:
    secret: ${spring.jwt.secret}
    access-token-valid-milliseconds: 172800000 # 2일
    refresh-token-valid-milliseconds: 5184000000  # 2달

  server:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  redis:
    host: ${spring.redis.host}
    port: 6379
  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    producer-topic : everyonepick.faceswap.request
    consumer-topic : everyonepick.faceswap.result


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: error

cloud:
  aws:
    credentials:
      access_key: ${cloud.aws.credentials.access_key}
      secret_key: ${cloud.aws.credentials.secret_key}
    s3:
      bucket: everyonepick-bucket
    region:
      static: ap-northeast-2

fcm:
  type: ${fcm.type}
  project_id: ${fcm.project_id}
  private_key_id: ${fcm.private_key_id}
  private_key: ${fcm.private_key}
  client_email: ${fcm.client_email}
  client_id: ${fcm.client_id}
  auth_uri: ${fcm.auth_uri}
  token_uri: ${fcm.token_uri}
  auth_provider_x509_cert_url: ${fcm.auth_provider_x509_cert_url}
  client_x509_cert_url: ${fcm.client_x509_cert_url}
